# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C++ workhorse
#' 
#' Calculate the segmentation given a value matrix and minimum streak
#'
#' @param values Matrix whose columns are streams to switch between
#' @param streak Minimum length between switches
smart_segment_cpp <- function(values, streak) {
    .Call('_smartsyncseg_smart_segment_cpp', PACKAGE = 'smartsyncseg', values, streak)
}

